import {Ionicons} from '@expo/vector-icons';import {router} from 'expo-router';import React,{useMemo,useState} from 'react';import {Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';import {PrimaryButton} from '@/src/components';import {useApp} from '@/src/store';import {colors,radius} from '@/src/theme';import {RecipeIngredient} from '@/src/types';
export default function NewRecipe(){const {foods,addRecipe}=useApp();const [title,setTitle]=useState('');const [serv,setServ]=useState('4');const [time,setTime]=useState('30');const [q,setQ]=useState('');const [ings,setIngs]=useState<RecipeIngredient[]>([]);const [steps,setSteps]=useState('');const list=useMemo(()=>q.length<2?[]:foods.filter(f=>f.normalizedName.includes(q.toLowerCase())).slice(0,8),[q,foods]);
const addIng=(id:string)=>{if(!ings.some(i=>i.foodId===id))setIngs(x=>[...x,{foodId:id,amount:100,unit:'g',grams:100}]);setQ('')};
const save=()=>{if(!title.trim()||ings.length===0)return;addRecipe({id:`custom_${Date.now()}`,title:title.trim(),category:'Plat',defaultServings:Number(serv)||1,timeMinutes:Number(time)||0,emoji:'🍽️',ingredients:ings,steps:steps.split('\n').map(x=>x.trim()).filter(Boolean),tags:['Perso'],custom:true});router.back()};
return <SafeAreaView style={{flex:1,backgroundColor:colors.bg}}><ScrollView contentContainerStyle={s.c}><Text onPress={()=>router.back()} style={s.close}>Fermer</Text><Text style={s.title}>Nouvelle recette</Text><TextInput value={title} onChangeText={setTitle} placeholder="Nom de la recette" style={s.input} placeholderTextColor={colors.muted}/><View style={{flexDirection:'row',gap:9}}><TextInput value={serv} onChangeText={setServ} keyboardType="numeric" placeholder="Parts" style={[s.input,{flex:1}]} placeholderTextColor={colors.muted}/><TextInput value={time} onChangeText={setTime} keyboardType="numeric" placeholder="Minutes" style={[s.input,{flex:1}]} placeholderTextColor={colors.muted}/></View>
<Text style={s.h}>Ingrédients</Text><TextInput value={q} onChangeText={setQ} placeholder="Rechercher un aliment" style={s.input} placeholderTextColor={colors.muted}/>{list.map(f=><Pressable key={f.id} onPress={()=>addIng(f.id)} style={s.food}><Text style={{flex:1,color:colors.text,fontWeight:'800'}}>{f.name}</Text><Text style={s.muted}>{f.state}</Text><Ionicons name="add-circle" size={23} color={colors.sage}/></Pressable>)}
{ings.map((i,idx)=>{const f=foods.find(x=>x.id===i.foodId)!;return <View key={i.foodId} style={s.ing}><Text style={{flex:1,color:colors.text}}>{f.name}</Text><TextInput keyboardType="numeric" value={String(i.amount)} onChangeText={v=>setIngs(a=>a.map((x,j)=>j===idx?{...x,amount:Number(v)||0,grams:Number(v)||0}:x))} style={s.qty}/><Text style={s.muted}>g</Text></View>})}
<Text style={s.h}>Étapes</Text><TextInput value={steps} onChangeText={setSteps} multiline placeholder={"Une étape par ligne\nCuire le riz\nFaire revenir le poulet…"} style={[s.input,{minHeight:110,textAlignVertical:'top'}]} placeholderTextColor={colors.muted}/><PrimaryButton label="Enregistrer la recette" onPress={save}/></ScrollView></SafeAreaView>}
const s=StyleSheet.create({c:{padding:18,paddingBottom:35,gap:10},close:{alignSelf:'flex-end',fontWeight:'900',color:colors.sageDark},title:{fontFamily:'Georgia',fontSize:34,fontWeight:'700',color:colors.text,marginBottom:4},input:{minHeight:48,borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:'#fff',paddingHorizontal:13,color:colors.text},h:{fontSize:17,fontWeight:'900',color:colors.text,marginTop:7},food:{minHeight:47,backgroundColor:'#fff',borderRadius:15,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8,borderWidth:1,borderColor:colors.border},muted:{fontSize:12,color:colors.muted},ing:{minHeight:48,backgroundColor:'#fff',borderRadius:15,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8,borderWidth:1,borderColor:colors.border},qty:{width:68,textAlign:'right',color:colors.text,fontWeight:'800'}})
