import {Ionicons} from '@expo/vector-icons';import {router,useLocalSearchParams} from 'expo-router';import React,{useState} from 'react';import {Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';import {PrimaryButton} from '@/src/components';import {useApp} from '@/src/store';import {colors,radius} from '@/src/theme';
export default function Feedback(){const {id}=useLocalSearchParams<{id:string}>();const {recipes,foods,saveFeedback}=useApp();const r=recipes.find(x=>x.id===id)!;const [q,setQ]=useState<'low'|'perfect'|'high'>('perfect');const [rating,setRating]=useState(4);const [note,setNote]=useState('');const [adj,setAdj]=useState<Record<string,number>>({});
return <SafeAreaView style={{flex:1,backgroundColor:colors.bg}}><ScrollView contentContainerStyle={s.c}><Pressable onPress={()=>router.back()} style={s.close}><Ionicons name="close" size={24} color={colors.text}/></Pressable><Text style={s.title}>Après le repas</Text><Text style={s.sub}>Aide Noma à s’adapter à toi. Tout reste privé.</Text><View style={s.recipe}><Text style={{fontSize:34}}>{r.emoji}</Text><View><Text style={s.rname}>{r.title}</Text><Text style={s.muted}>Feedback privé</Text></View></View>
<View style={s.card}><Text style={s.h}>Quantité globale</Text><Text style={s.muted}>Est-ce qu’il en restait assez ?</Text><View style={s.pills}>{[['low','Pas assez'],['perfect','Parfait'],['high','Trop']].map(([v,l])=><Pressable key={v} onPress={()=>setQ(v as any)} style={[s.pill,q===v&&s.pillOn]}><Text style={[s.pillT,q===v&&{color:'#fff'}]}>{l}</Text></Pressable>)}</View></View>
<View style={s.card}><Text style={s.h}>Ingrédients à ajuster</Text><Text style={s.muted}>Optionnel · ±10 % à chaque pression.</Text>{r.ingredients.map(i=>{const f=foods.find(x=>x.id===i.foodId)!;return <View key={i.foodId} style={s.ing}><Text style={{flex:1,color:colors.text}}>{f.name}</Text><Pressable style={s.tiny} onPress={()=>setAdj(a=>({...a,[i.foodId]:Math.max(-.3,(a[i.foodId]||0)-.1)}))}><Ionicons name="remove" size={15} color={colors.sageDark}/></Pressable><Text style={s.adj}>{Math.round((adj[i.foodId]||0)*100)}%</Text><Pressable style={s.tiny} onPress={()=>setAdj(a=>({...a,[i.foodId]:Math.min(.5,(a[i.foodId]||0)+.1)}))}><Ionicons name="add" size={15} color={colors.sageDark}/></Pressable></View>})}</View>
<View style={s.card}><Text style={s.h}>Ta note</Text><View style={s.stars}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>setRating(n)}><Ionicons name={n<=rating?'star':'star-outline'} size={29} color={colors.sage}/></Pressable>)}</View></View>
<View style={s.card}><Text style={s.h}>Note perso</Text><TextInput value={note} onChangeText={setNote} multiline placeholder="Ex. plus épicé, moins de cuisson…" placeholderTextColor={colors.muted} style={s.input}/></View>
<PrimaryButton label="Enregistrer" onPress={()=>{saveFeedback(id,q,rating,note,adj);router.back()}}/></ScrollView></SafeAreaView>}
const s=StyleSheet.create({c:{padding:18,paddingBottom:35},close:{alignSelf:'flex-end',width:40,height:40,alignItems:'center',justifyContent:'center'},title:{fontFamily:'Georgia',fontSize:38,fontWeight:'700',color:colors.text},sub:{color:colors.muted,fontSize:15,marginTop:4,marginBottom:14},recipe:{flexDirection:'row',gap:10,alignItems:'center',marginBottom:10},rname:{fontSize:18,fontWeight:'900',color:colors.text},muted:{fontSize:12.5,color:colors.muted,marginTop:3},card:{backgroundColor:'#fff',borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,padding:16,marginBottom:10},h:{fontSize:16,fontWeight:'900',color:colors.text},pills:{flexDirection:'row',gap:7,marginTop:12},pill:{flex:1,borderRadius:999,borderWidth:1,borderColor:colors.border,paddingVertical:10,alignItems:'center'},pillOn:{backgroundColor:colors.sage,borderColor:colors.sage},pillT:{fontWeight:'800',color:colors.text,fontSize:13},ing:{minHeight:47,borderTopWidth:1,borderTopColor:'#F0F2EE',flexDirection:'row',alignItems:'center',gap:7},tiny:{width:29,height:29,borderRadius:15,backgroundColor:colors.sageSoft,alignItems:'center',justifyContent:'center'},adj:{minWidth:38,textAlign:'center',fontWeight:'900',color:colors.text},stars:{flexDirection:'row',gap:8,marginTop:10},input:{minHeight:82,borderRadius:16,backgroundColor:'#F5F7F3',padding:12,marginTop:10,color:colors.text,textAlignVertical:'top'}})
