import {Ionicons} from '@expo/vector-icons';import {router,useLocalSearchParams} from 'expo-router';import React,{useMemo,useState} from 'react';import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';import {PrimaryButton} from '@/src/components';import {recipeNutrition,roundMacro} from '@/src/nutrition';import {useApp} from '@/src/store';import {colors,radius} from '@/src/theme';
export default function Detail(){const {id}=useLocalSearchParams<{id:string}>();const {recipes,foods,learning,goals}=useApp();const r=recipes.find(x=>x.id===id)!;const l=learning[id];const [serv,setServ]=useState(r.defaultServings);const scale=serv/r.defaultServings;const n=recipeNutrition(r,foods,l,serv);const per={kcal:n.kcal/serv,protein:n.protein/serv,carbs:n.carbs/serv,fat:n.fat/serv};
return <ScrollView contentContainerStyle={s.c}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="chevron-back" size={25} color={colors.text}/></Pressable><Text style={s.title}>{r.title}</Text><View style={s.hero}><Text style={{fontSize:82}}>{r.emoji}</Text></View>
<View style={s.serv}><Pressable onPress={()=>setServ(Math.max(1,serv-1))} style={s.round}><Ionicons name="remove" size={22} color={colors.sageDark}/></Pressable><View><Text style={s.servN}>{serv}</Text><Text style={s.small}>parts</Text></View><Pressable onPress={()=>setServ(serv+1)} style={[s.round,{backgroundColor:colors.sage}]}><Ionicons name="add" size={22} color="#fff"/></Pressable></View>
{goals.enabled?<View style={s.macros}>{[['kcal',Math.round(per.kcal),'kcal'],['prot',roundMacro(per.protein),'g'],['gluc',roundMacro(per.carbs),'g'],['lip',roundMacro(per.fat),'g']].map(([k,v,u])=><View key={k as string} style={s.macro}><Text style={s.macroN}>{v}</Text><Text style={s.small}>{u} {k!=='kcal'?k:''}</Text></View>)}</View>:null}
<View style={s.card}><View style={s.head}><Text style={s.h}>Ingrédients</Text><Text style={s.small}>{serv} parts</Text></View>{r.ingredients.map(i=>{const f=foods.find(x=>x.id===i.foodId)!;const im=l?.ingredientMultipliers?.[i.foodId]||1;const qty=i.amount*scale*(l?.overallMultiplier||1)*im;return <View key={i.foodId} style={s.row}><Text style={s.item}>{f.name}</Text><Text style={s.qty}>{Math.round(qty*10)/10} {i.unit}</Text></View>})}</View>
<View style={s.card}><Text style={s.h}>Étapes</Text>{r.steps.map((x,i)=><View key={i} style={s.step}><View style={s.stepN}><Text style={{fontWeight:'900',color:colors.sageDark}}>{i+1}</Text></View><Text style={{flex:1,color:colors.text,lineHeight:21}}>{x}</Text></View>)}</View>
{l?<View style={s.learn}><Ionicons name="sparkles-outline" size={22} color={colors.sageDark}/><View style={{flex:1}}><Text style={s.h}>Chez toi</Text><Text style={s.small}>{l.notes.at(-1)||'Cette recette a déjà été adaptée.'}</Text></View><Ionicons name="checkmark-circle" size={23} color={colors.sage}/></View>:null}
<PrimaryButton label="Après le repas" icon="sparkles-outline" onPress={()=>router.push(`/feedback/${r.id}`)}/></ScrollView>}
const s=StyleSheet.create({c:{paddingHorizontal:18,paddingTop:58,paddingBottom:35},back:{width:40,height:40,justifyContent:'center'},title:{fontFamily:'Georgia',fontSize:36,fontWeight:'700',color:colors.text,marginBottom:12},hero:{height:210,borderRadius:radius.lg,backgroundColor:colors.beige,alignItems:'center',justifyContent:'center',marginBottom:12},serv:{backgroundColor:'#fff',borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,padding:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:34},round:{width:44,height:44,borderRadius:22,backgroundColor:colors.sageSoft,alignItems:'center',justifyContent:'center'},servN:{fontSize:27,fontWeight:'900',color:colors.text,textAlign:'center'},small:{fontSize:12,color:colors.muted,marginTop:2},macros:{flexDirection:'row',backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:radius.md,marginTop:10,overflow:'hidden'},macro:{flex:1,alignItems:'center',padding:11,borderRightWidth:1,borderRightColor:colors.border},macroN:{fontWeight:'900',color:colors.text},card:{backgroundColor:'#fff',borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,padding:16,marginTop:11},head:{flexDirection:'row',justifyContent:'space-between'},h:{fontSize:17,fontWeight:'900',color:colors.text,marginBottom:8},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:9,borderTopWidth:1,borderTopColor:'#F0F2EE'},item:{color:colors.text},qty:{color:colors.muted},step:{flexDirection:'row',gap:10,paddingVertical:8},stepN:{width:27,height:27,borderRadius:14,backgroundColor:colors.sageSoft,alignItems:'center',justifyContent:'center'},learn:{flexDirection:'row',gap:11,alignItems:'center',padding:15,borderRadius:radius.lg,backgroundColor:colors.sageSoft,marginVertical:11}})
