import {Ionicons} from '@expo/vector-icons';import {router} from 'expo-router';import React,{useMemo,useState} from 'react';import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {ScreenTitle} from '@/src/components';import {dayShort,isoDay,mondayOf,monthShort,weekDays} from '@/src/date';import {recipeNutrition,roundMacro} from '@/src/nutrition';import {useApp} from '@/src/store';import {colors,radius} from '@/src/theme';import {MealType} from '@/src/types';
const slots:[MealType,string,keyof typeof Ionicons.glyphMap][]=[['breakfast','Petit-déj','cafe-outline'],['lunch','Déjeuner','sunny-outline'],['dinner','Dîner','moon-outline']];
export default function Week(){
 const {recipes,foods,plan,learning,goals,changeServings}=useApp();const days=useMemo(()=>weekDays(mondayOf()),[]);const ti=days.findIndex(d=>isoDay(d)===isoDay(new Date()));const [sel,setSel]=useState(ti>=0?ti:0);const d=days[sel],key=isoDay(d),day=plan[key]||{};
 const dayMacros=Object.values(day).reduce((a,m)=>{if(!m)return a;const r=recipes.find(x=>x.id===m.recipeId);if(!r)return a;const n=recipeNutrition(r,foods,learning[r.id],m.servings);a.kcal+=n.kcal;a.protein+=n.protein;a.carbs+=n.carbs;a.fat+=n.fat;return a},{kcal:0,protein:0,carbs:0,fat:0});
 return <ScrollView contentContainerStyle={s.container} showsVerticalScrollIndicator={false}><ScreenTitle title="Noma" subtitle={`Semaine du ${days[0].getDate()} ${monthShort[days[0].getMonth()]} au ${days[6].getDate()} ${monthShort[days[6].getMonth()]}`}/>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.days}>{days.map((x,i)=>{const active=i===sel,count=Object.keys(plan[isoDay(x)]||{}).length;return <Pressable key={i} onPress={()=>setSel(i)} style={[s.day,active&&s.dayOn]}><Text style={[s.dayName,active&&s.white]}>{dayShort[x.getDay()]}</Text><Text style={[s.dayNum,active&&s.white]}>{x.getDate()}</Text><View style={[s.dot,count>0&&{backgroundColor:active?'#DCE6D7':colors.sage}]}/></Pressable>})}</ScrollView>
 <View style={s.head}><View><Text style={s.h2}>{dayShort[d.getDay()]} {d.getDate()} {monthShort[d.getMonth()]}</Text><Text style={s.muted}>3 moments, à ton rythme.</Text></View><View style={s.counter}><Text style={s.counterT}>{Object.keys(day).length}/3</Text></View></View>
 {goals.enabled?<View style={s.macroCard}><View><Text style={s.macroBig}>{Math.round(dayMacros.kcal)} <Text style={s.macroSmall}>/ {goals.kcal} kcal</Text></Text><Text style={s.muted}>{Math.round(dayMacros.protein)} g prot · {Math.round(dayMacros.carbs)} g gluc · {Math.round(dayMacros.fat)} g lip</Text></View><View style={s.progress}><View style={[s.progressFill,{width:`${Math.min(100,dayMacros.kcal/goals.kcal*100)}%`}]}/></View></View>:null}
 <View style={{gap:11}}>{slots.map(([type,label,icon])=>{const pm=day[type],r=pm?recipes.find(x=>x.id===pm.recipeId):undefined;return <View key={type} style={s.meal}><View style={s.mealLabel}><Ionicons name={icon} size={18} color={colors.sageDark}/><Text style={s.mealLabelT}>{label}</Text></View>
 {r&&pm?<Pressable style={s.mealBody} onPress={()=>router.push(`/recipe/${r.id}`)}><View style={s.emoji}><Text style={{fontSize:27}}>{r.emoji}</Text></View><View style={{flex:1}}><Text style={s.recipe}>{r.title}</Text><Text style={s.muted}>{r.timeMinutes} min · {pm.servings} part{pm.servings>1?'s':''}</Text></View><View style={s.stepper}><Pressable onPress={e=>{e.stopPropagation();changeServings(key,type,-1)}} style={s.round}><Ionicons name="remove" size={16} color={colors.sageDark}/></Pressable><Text style={s.stepN}>{pm.servings}</Text><Pressable onPress={e=>{e.stopPropagation();changeServings(key,type,1)}} style={s.round}><Ionicons name="add" size={16} color={colors.sageDark}/></Pressable></View></Pressable>:
 <Pressable style={s.add} onPress={()=>router.push({pathname:'/pick-recipe',params:{date:key,meal:type}})}><Ionicons name="add" size={20} color={colors.sageDark}/><Text style={s.addT}>Ajouter {label.toLowerCase()}</Text></Pressable>}</View>})}</View>
 </ScrollView>
}
const s=StyleSheet.create({container:{paddingHorizontal:18,paddingTop:62,paddingBottom:35},days:{gap:8,paddingBottom:18},day:{width:54,height:76,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},dayOn:{backgroundColor:colors.sage,borderColor:colors.sage},dayName:{fontSize:12,fontWeight:'800',color:colors.muted},dayNum:{fontSize:20,fontWeight:'900',color:colors.text,marginTop:2},white:{color:'#fff'},dot:{width:5,height:5,borderRadius:3,marginTop:6},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},h2:{fontSize:22,fontWeight:'900',color:colors.text},muted:{color:colors.muted,fontSize:13,marginTop:3},counter:{backgroundColor:colors.sageSoft,paddingVertical:7,paddingHorizontal:12,borderRadius:999},counterT:{color:colors.sageDark,fontWeight:'900'},macroCard:{backgroundColor:colors.sageSoft,borderRadius:radius.lg,padding:15,marginBottom:12},macroBig:{fontSize:22,fontWeight:'900',color:colors.text},macroSmall:{fontSize:13,color:colors.muted,fontWeight:'700'},progress:{height:6,backgroundColor:'#D8E2D3',borderRadius:999,overflow:'hidden',marginTop:10},progressFill:{height:6,backgroundColor:colors.sage},meal:{backgroundColor:'#fff',borderRadius:radius.lg,padding:14,borderWidth:1,borderColor:colors.border},mealLabel:{flexDirection:'row',alignItems:'center',gap:7,marginBottom:10},mealLabelT:{fontWeight:'900',fontSize:14,color:colors.text},mealBody:{flexDirection:'row',alignItems:'center',gap:11},emoji:{width:53,height:53,borderRadius:17,backgroundColor:colors.beige,alignItems:'center',justifyContent:'center'},recipe:{fontSize:17,fontWeight:'900',color:colors.text},stepper:{flexDirection:'row',alignItems:'center',gap:6},round:{width:29,height:29,borderRadius:15,backgroundColor:colors.sageSoft,alignItems:'center',justifyContent:'center'},stepN:{minWidth:15,textAlign:'center',fontWeight:'900',color:colors.text},add:{borderWidth:1.2,borderStyle:'dashed',borderColor:'#CAD5C7',backgroundColor:'#FAFCF9',borderRadius:18,padding:13,flexDirection:'row',gap:8,alignItems:'center'},addT:{color:colors.sageDark,fontWeight:'900'}})
