import {Ionicons} from '@expo/vector-icons';import React from 'react';import {Pressable,ScrollView,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import {ScreenTitle} from '@/src/components';import {useApp} from '@/src/store';import {colors,radius} from '@/src/theme';
export default function Profile(){const {goals,setGoals,householdSize,setHouseholdSize,learning,resetDemo}=useApp();return <ScrollView contentContainerStyle={s.container}><ScreenTitle title="Profil" subtitle="Seulement les réglages qui comptent."/>
<View style={s.card}><Text style={s.h}>Foyer</Text><View style={s.step}><Pressable style={s.round} onPress={()=>setHouseholdSize(householdSize-1)}><Ionicons name="remove" size={18} color={colors.sageDark}/></Pressable><View><Text style={s.big}>{householdSize}</Text><Text style={s.muted}>personnes par défaut</Text></View><Pressable style={s.round} onPress={()=>setHouseholdSize(householdSize+1)}><Ionicons name="add" size={18} color={colors.sageDark}/></Pressable></View></View>
<View style={s.card}><View style={s.toggle}><View style={{flex:1}}><Text style={s.h}>Macros</Text><Text style={s.muted}>Afficher calories, protéines, glucides et lipides.</Text></View><Switch value={goals.enabled} onValueChange={v=>setGoals({enabled:v})} trackColor={{true:colors.sage,false:'#D7DDD5'}}/></View>
{goals.enabled?<View style={s.grid}>{[['kcal','kcal'],['protein','g prot'],['carbs','g gluc'],['fat','g lip']].map(([k,l])=><View key={k} style={s.target}><TextInput keyboardType="numeric" value={String((goals as any)[k])} onChangeText={v=>setGoals({[k]:Number(v)||0} as any)} style={s.input}/><Text style={s.muted}>{l} / jour</Text></View>)}</View>:null}</View>
<View style={[s.card,{backgroundColor:colors.sageSoft}]}><Text style={s.h}>Noma apprend</Text><Text style={s.muted}>{Object.keys(learning).length} recette(s) adaptée(s) à tes retours. Les recettes originales restent intactes.</Text></View>
<Pressable onPress={resetDemo} style={s.reset}><Ionicons name="refresh" size={18} color={colors.sageDark}/><Text style={{fontWeight:'900',color:colors.sageDark}}>Réinitialiser la démo</Text></Pressable></ScrollView>}
const s=StyleSheet.create({container:{paddingHorizontal:18,paddingTop:62,paddingBottom:35,gap:11},card:{backgroundColor:'#fff',borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,padding:17},h:{fontSize:17,fontWeight:'900',color:colors.text},muted:{fontSize:12.5,color:colors.muted,marginTop:3,lineHeight:18},step:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:16},round:{width:42,height:42,borderRadius:21,backgroundColor:colors.sageSoft,alignItems:'center',justifyContent:'center'},big:{fontSize:25,fontWeight:'900',color:colors.text,textAlign:'center'},toggle:{flexDirection:'row',alignItems:'center',gap:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:9,marginTop:15},target:{width:'48%',backgroundColor:'#FAFBF8',borderRadius:18,padding:12},input:{fontSize:20,fontWeight:'900',color:colors.text,padding:0},reset:{flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center',padding:17}})
